# Generated by Django 3.2.9 on 2021-11-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(default='https://ui-avatars.com/api/?name=<django.db.models.fields.CharField>+<django.db.models.fields.CharField>&background=0D8ABC&color=fff', max_length=256),
        ),
    ]
