# Generated by Django 3.2.8 on 2021-10-23 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.TextField(max_length=512)),
                ('expectation', models.TextField(max_length=512)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('mentee_id', models.CharField(max_length=32)),
                ('mentor_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('link', models.CharField(max_length=128)),
                ('room_id', models.CharField(max_length=64)),
                ('mentorship', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mentorship.mentorship')),
            ],
            options={
                'db_table': 'mentorship_response',
            },
        ),
    ]
